timeout = 120
extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args} -t traces/{base}.trace",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "racket src/compiler.rkt --spec traces/{base}.trace",
    "brili -p {args}",
]

