timeout = 120
extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "racket src/compiler.rkt --ssa",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "racket src/compiler.rkt --ssa --licm",
    "brili -p {args}",
]
